### ISSUE TITLE
Silk over vias

### ISSUE THREAD

**Issue by silardg** [heyspacebuck/double-oh#5]
First of all, big fan!

I noticed that the silk (example U2) is over a VIA, which won't look good when manufactured.

**Comment by heyspacebuck** [comment]
Thank you for your attention to detail! I have noticed this as well, but until now I had considered it just a minor nuisance. The image at the top of the readme is *very* outdated, since then I have removed all the references from the top of the board; the only remaining silks are on the back of the board and I think they are all legible despite the presence of vias. Again, thanks for writing!
